In [17]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

dataset = pd.read_csv('Dataset_Banjir.csv') 
x = dataset.iloc[:, :-1].values # untuk atribut
y = dataset.iloc[:, -1].values  # untuk class

In [20]:
print(x)

[['Kudus' 33.0 5 3.0]
 ['Pati' 3137.0 73 4.0]
 ['Rembang' 987.0 16 1.0]
 ['Jepara' nan 3 1.0]
 ['Grobogan' 499.0 30 6.0]
 ['Blora' 388.0 13 nan]
 ['Tegal' 3103.0 18 1.0]
 ['Brebes' 638.0 11 nan]]


In [23]:
print(y)

['no' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes']


In [21]:
# untuk mengisi missing value (nan) dengan nilai rata2 (mean)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [22]:
print(x)

[['Kudus' 33.0 5.0 3.0]
 ['Pati' 3137.0 73.0 4.0]
 ['Rembang' 987.0 16.0 1.0]
 ['Jepara' 1255.0 3.0 1.0]
 ['Grobogan' 499.0 30.0 6.0]
 ['Blora' 388.0 13.0 2.6666666666666665]
 ['Tegal' 3103.0 18.0 1.0]
 ['Brebes' 638.0 11.0 2.6666666666666665]]


In [24]:
#function untuk mengubah baris awal string menjadi angka
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 33.0 5.0 3.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 3137.0 73.0 4.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 987.0 16.0 1.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1255.0 3.0 1.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 499.0 30.0 6.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 388.0 13.0 2.6666666666666665]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 3103.0 18.0 1.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 638.0 11.0 2.6666666666666665]]


In [26]:
from sklearn.preprocessing import LabelEncoder # function utk mengubah label yg yes no menjadi numerik
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
print(y)

[0 1 1 0 1 1 1 1]


In [28]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1) 
# 0.2 artinya 20% utk test, dan sisanya 80% untuk train

In [29]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 3137.0 73.0 4.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 3103.0 18.0 1.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 33.0 5.0 3.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 499.0 30.0 6.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1255.0 3.0 1.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 388.0 13.0 2.6666666666666665]]


In [30]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 638.0 11.0 2.6666666666666665]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 987.0 16.0 1.0]]


In [31]:
print(y_train)

[1 1 0 1 0 1]


In [32]:
print(y_test)

[1 1]


In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 8:] = sc.fit_transform(x_train[:, 8:])
x_test[:, 8:] = sc.transform(x_test[:, 8:])

In [36]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.368181951999036 2.0738382353758866
  0.6078638537434348]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.341362588281557 -0.23821114865804105
  -1.1197492042642219]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 -1.0802681944437473 -0.7846955485206057
  0.03199283440754923]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 -0.7126851505512418 0.2662359896766341
  1.759605892415206]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 -0.1163487102449454 -0.8687700715763851
  -1.1197492042642219]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.8002424850406584 -0.448397456297489
  -0.15996417203774607]]


In [37]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.6030412812356661 -0.5324719793532683
  -0.15996417203774607]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 -0.32774840072389705
  -0.3222856717138202 -1.1197492042642219]]
